### PR TITLE
revise the membership page

### PR DESCRIPTION
**Pull request by mojavelinux**
* fix the "To for the discussion the discussion" sentence
* rephase the point about taking on more responsibility
* rephrase the description about the group's function
* add missing commas in the description of Committer members

### CODE REVIEW

**Comment by Mogztter** [comment]
You will need to amend your commit to update your email address (dan.j.allen@... is not attached to your Eclipse account)

**Comment by mojavelinux** [comment]
I'm using the correct email address. I don't understand why the check is failing.

**Comment by autumnfound** [comment]
> I'm using the correct email address. I don't understand why the check is failing.

I'll be honest, I'm not sure why its failing either, huh. I'll poke @ericpoirier as he's been working around that code more than I have been.

**Comment by mojavelinux** [comment]
@autumnfound Thanks for looking into this matter. I'm certainly eager to see these changes get merged.

**Comment by chrisguindon** [comment]
@mojavelinux We are working on the issue. However, it's clear to me that you do have an ECA on file. You can merge your changes while we work on this issue for you.

**Comment by chrisguindon** [comment]
@mojavelinux @ahus1 We believe the validation issues are now fixed.

**Comment by mojavelinux** [comment]
Thanks @chrisguindon! I have one more PR to submit, so I'll make that the test.

**Pull request merged**
