### PR TITLE
update logo to be different from main Eclipse site (#57)

### LINKED ISSUE #57: Updating banner image
We noticed that the site is using the same banner image as eclipse.org, which may be confusing for some people. To help give AsciiDoc it's own look we have mocked up a couple of options for updated banner images. Let us know which (if either) you prefer and we can add the image files to the bug once you've provided your feedback.

Option A:
AsciiDoc Banner A - People

Option B:
AsciiDoc Banner B - Abstract

### PR DESCRIPTION
**Pull request by ahus1**
closes #57

### CODE REVIEW

**Comment by autumnfound** [comment]
The update looks good, the image is present! I'm a little concerned about how the text looks over the bright colours. We may want to consider a way to address this. We could use the site params `jumbotron_class` and `jumbotron_tagline_class` to affect the look and feel of this section, but I'm not totally sure what the best way to do this is

**Comment by autumnfound** [comment]
image

**Comment by autumnfound** [comment]
Ahh Mehrnaz beat me to it! A starting point for this may be:

jumbotron_class = "col-xs-24 col-sm-18 col-lg-16 text-left"
jumbotron_tagline_class = "col-xs-24 col-sm-18 col-lg-16 text-left"

**Comment by ahus1** [comment]
@autumnfound - let's discuss in the main issue what this is about: changing the background image, or styling the header in some other way.

**Review by autumnfound — APPROVED** [review]

**Pull request merged**
