### PR TITLE
Add Eclipse Austen project

### LINKED ISSUE #61: Add Eclipse Austen as a project to the WG site
The project Eclipse Austen currently being setup/created. https://projects.eclipse.org/proposals/eclipse-austen

Once it is ready, it should be on the WG's project list: https://asciidoc-wg.eclipse.org/projects/

@abelsromero - could you please take on this task once Eclipse Austen should appear on the WG's site?

Content goes here: https://github.com/EclipseFdn/asciidoc-wg.eclipse.org/tree/main/content/projects
The Hugo setup would require a new folder _austen_ as a sibling to the folder _asciidoc-lang_ with similar content. 

Thanks!

### PR DESCRIPTION
**Pull request by abelsromero**
Closes #61

### CODE REVIEW

**Comment by abelsromero** [comment]
Stupid question...I wanted to add an option to add Code repo button next to the Website button, but couldn't find where the labels are defined, not even search for the labels "Website" or "Download" :open_mouth:

**Comment by autumnfound** [comment]
> Stupid question...I wanted to add an option to add Code repo button next to the Website button, but couldn't find where the labels are defined, not even search for the labels "Website" or "Download"

This is created from a layout file in the base theme for projects seen here: https://github.com/EclipseFdn/hugo-solstice-theme/blob/master/layouts/projects/summary.html. If you wanted to add a code repo button, you could probably make a pull request to add it (with some checking to only print it when we have it). It can be tricky to find so I don't blame you!

**Comment by abelsromero** [comment]
> This is created from a layout file in the base theme for projects seen here: https://github.com/EclipseFdn/hugo-solstice-theme/blob/master/layouts/projects/summary.html. If you wanted to add a code repo button, you could probably make a pull request to add it (with some checking to only print it when we have it). It can be tricky to find so I don't blame you!

That's not the issue, the thing is where do the literals come from? I was expecting this `{{ i18n "project-summary-website-label" }}` to point to some property/json/yaml with that key but could not find it, even searching by "Website" wicth the value did not bring results.

**Comment by autumnfound** [comment]
> > This is created from a layout file in the base theme for projects seen here: https://github.com/EclipseFdn/hugo-solstice-theme/blob/master/layouts/projects/summary.html. If you wanted to add a code repo button, you could probably make a pull request to add it (with some checking to only print it when we have it). It can be tricky to find so I don't blame you!
> 
> That's not the issue, the thing is where do the literals come from? I was expecting this `{{ i18n "project-summary-website-label" }}` to point to some property/json/yaml with that key but could not find it, even searching by "Website" which the value did not bring results.

Ahh! Gotcha. i18n labels are stored in the i18n folder in the root of the project, in line with whats defined on the [Hugo documentation for i18n](https://gohugo.io/functions/i18n/). That particular value is set in the following file: https://github.com/EclipseFdn/hugo-solstice-theme/blob/master/i18n/en.toml#L208

**Comment by ahus1** [comment]
@abelsromero - I see you link to the project proposal. AFAIK this page is immutable once the project is created. 

The project page is: https://projects.eclipse.org/projects/technology.austen

The biggest difference: The project page contains the Git repo link, while the project proposal doesn't. 

Therefore I suggest: please update the URL to point at the project page.

**Comment by abelsromero** [comment]
> refore I suggest: please update the URL to point at the project page.

Fixed, many thanks for the verification

**Pull request merged**
